on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Compiles all writeups to a database
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/compile # Compile metadata
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "compiled.sqlite3"
          tag: ${{ github.event.head_commit.id }}
          token: ${{ secrets.GITHUB_TOKEN }}