on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/compile # Compile metadata
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "compiled.sqlite3"
