on: [push]

jobs:
  compile_metadata:
    runs-on: ubuntu-latest
    name: Compiles all writeups to a database
    permissions:
      contents: write
    steps:
      - name: Get short commit SHA
        id: shortsha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: ./.github/actions/compile # Compile metadata
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "compiled.sqlite3"
          tag: ${{ steps.shortsha.outputs.SHORT_SHA }}
          commit: ${{ github.event.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true